name: Build and execute Python script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Setup
        uses: ./.github/actions/setup

      - name: Execution de pytest
        run: coverage run -m pytest; coverage xml

      - name: Python Coverage
        uses: orgoro/coverage@v3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          coverageFile: coverage.xml
  release:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: major
          use_github_release_notes: true

#  notify:
#    runs-on: ubuntu-latest
#    needs: release
#    if: always()

