name: Build and execute Python script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Setup
        uses: ./.github/actions/setup

      - name: Execution de pytest
        run: coverage run -m pytest; coverage xml

      - name: Python Coverage
        uses: orgoro/coverage@v3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          coverageFile: coverage.xml


